version: '2'
services:
  prometheus:
    build: .
    container_name: prometheus
    ports:
     - "9090:9090"
#    volumes:
#     - $PWD/prometheus-data:/etc/prometheus/data
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9100:9100
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    # volumes:
    #   - ./grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
