version: '2'
services:
  prometheus:
    build: .
    container_name: prometheus
    ports:
     # - "9090:9090"
     - "8080:9090"
#    volumes:
#     - $PWD/prometheus-data:/etc/prometheus/data
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9100:9100
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    # volumes:
    #   - ./grafana-data:/var/lib/grafana
    ports:
      # - 3000:3000
      - 8081:3000

  # nginx:
  #   container_name: nginx
  #   image: nginx:1.13.6-alpine
  #   volumes:
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf/conf.d:/etc/nginx/conf.d
  #     - ./nginx/_log:/var/log/nginx
  #   ports:
  #     #- 80:80
  #     - 8080:8080
  #   links:
  #     - grafana
  #     - prometheus
